services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=vericase
      - POSTGRES_PASSWORD=vericase123
      - POSTGRES_DB=vericase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    image: wcjrogers/vericase-api:latest
    ports:
      - 8010:8000
    depends_on:
      - db
      - redis
    volumes:
      - ./ui:/code/ui
    environment:
      - JWT_SECRET=c3bef73578895c08045f8848192958b2dbfaf55a57f97509553c3d5324a7d2b1
      - DEV_NO_AUTH=true
      - DATABASE_URL=postgresql://vericase:vericase123@db:5432/vericase
      - REDIS_URL=redis://redis:6379/0
      - USE_AWS_SERVICES=true
      - AWS_REGION=eu-west-2
      - S3_BUCKET=vericase-docs
    restart: unless-stopped

  worker:
    image: wcjrogers/vericase-api:latest
    command: ["celery", "-A", "worker_app.worker", "worker", "-Q", "celery", "--loglevel=info", "--concurrency=2"]
    depends_on:
      - db
      - redis
    environment:
      - JWT_SECRET=c3bef73578895c08045f8848192958b2dbfaf55a57f97509553c3d5324a7d2b1
      - DEV_NO_AUTH=true
      - DATABASE_URL=postgresql+psycopg2://vericase:vericase123@db:5432/vericase
      - REDIS_URL=redis://redis:6379/0
      - USE_AWS_SERVICES=true
      - AWS_REGION=eu-west-2
      - S3_BUCKET=vericase-docs
      - OPENSEARCH_HOST=search-vericase-es-dev-rg4lhptqjlqfha7nmmm3xeubhy.eu-west-2.es.amazonaws.com
      - OPENSEARCH_PORT=443
      - OPENSEARCH_USE_SSL=true
      - OPENSEARCH_VERIFY_CERTS=true
      - USE_TEXTRACT=true
    restart: unless-stopped

volumes:
  postgres-data:
