services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=vericase
      - POSTGRES_PASSWORD=vericase123
      - POSTGRES_DB=vericase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: wcjrogers/vericase-api:latest
    ports:
      - 8010:8000
    depends_on:
      - db
    environment:
      - JWT_SECRET=c3bef73578895c08045f8848192958b2dbfaf55a57f97509553c3d5324a7d2b1
      - DEV_NO_AUTH=true
      - DATABASE_URL=postgresql://vericase:vericase123@db:5432/vericase
      - USE_AWS_SERVICES=true
      - AWS_REGION=eu-west-2
      - S3_BUCKET=vericase-docs
    restart: unless-stopped

volumes:
  postgres-data:
